<?xml version="1.0" encoding="ISO-8859-1"?>
<ivy-module version="2.0" 
			xmlns:ea="http://www.easyant.org"
			xmlns:m="http://ant.apache.org/ivy/maven">
    <info organisation="net.sourceforge.beet" module="beet-test" revision="1.4.0_rc1">
		<extends organisation="net.sourceforge.beet" name="beet" revision="latest.integration"/>
		
    	<license name="Mozilla Public License, version 1.1" 
    			 url="http://www.mozilla.org/MPL/MPL-1.1.html"/>
    	<repository name="Beet Ivyrep" url="http://beet.sourceforge.net/ivyrep"
    				pattern="[organisation]/[module]/[revision]/[type]s/[artifact].[ext]"/>
    	<description homepage="http://beet.sourceforge.net">
    	Unit testing utilities developed as a corollary of the beet project.
    	</description>
    	
		<ea:build type="org.apache.easyant.buildtypes#build-std-java;0.2">
			<ea:property name="main.confs" value="compile"/>
			<ea:plugin module="org.apache.easyant.plugins#source-jar;0.1" mandatory="true" as="source-jar"/>
		</ea:build>
		
	</info>
	
	<configurations>
		<conf name="base" description="core module without runtime dependencies"/>
		<conf name="source" description="source jar"/>
		<conf name="javadoc" description="docs jar"/>
		<conf name="compile" description="compile-time dependencies"/>
		<conf name="test" description="dependencies used for junit testing"/>
		
		<conf name="1.5" extends="default" description="core module with dependencies, for SDK 1.5 and below"/>
		<conf name="1.6" description="core module with runtime dependencies, for SDK 1.6 and higher"/>
		<conf name="default" extends="1.6" description="alias for '1.6'" />
	</configurations>

	<publications>
		<artifact name="beet-test" type="jar" conf="base,default,test"/>
		<artifact name="beet-test" type="source" ext="jar" conf="source" m:classifier="source"/>
		<artifact name="beet-test" type="javadoc" ext="zip" conf="javadoc" m:classifier="javadoc"/>
	</publications>
	
	<dependencies defaultconfmapping="1.5,1.6,default,compile,test->default">

		<dependency org="org.unitils" name="unitils" rev="2.3"/>
		<dependency org="org.apache.tomcat" name="catalina" rev="6.0.18"/>
		<dependency org="org.apache.tomcat" name="coyote" rev="6.0.18"/>
		<dependency org="org.apache.tomcat" name="jsp-api" rev="6.0.18"/>
		<dependency org="org.apache.tomcat" name="jasper" rev="6.0.18"/>
		
		<dependency org="org.springframework" name="spring-beans" rev="2.0.+" conf="compile"/>
		<dependency org="org.springframework" name="spring-core" rev="2.0.+" conf="compile"/>
		<dependency org="org.springframework" name="spring-context" rev="2.0.+" conf="compile"/>

		<dependency org="junit" name="junit" rev="4.4" conf="test"/>
		<dependency org="net.sourceforge.htmlunit" name="htmlunit" rev="2.1" conf="test"/>
		
	</dependencies>
	
</ivy-module>
