-- use with <jdbc-persister dialect="uuid" />
create table BEHAVIOR_TRACKING_EVENT (
	EVENT_ID 		CHAR(36)		PRIMARY KEY,
	PARENT_EVENT_ID CHAR(36), 
	EVENT_TYPE		VARCHAR(20)		NOT NULL,
	EVENT_NAME		VARCHAR(256)	NOT NULL,
	EVENT_START		DATE			NOT NULL,
	USER_ID			VARCHAR(64),
	SESSION_ID		VARCHAR(64),
	APPLICATION		VARCHAR(64)		NOT NULL,
	DURATION_NS		BIGINT			NOT NULL,
	EVENT_DATA		VARCHAR(4000),
	ERROR			VARCHAR(512)
);
