LOAD DATA INFILE '/tmp/import-mysql.fifo'
    INTO TABLE BEHAVIOR_TRACKING_EVENT
    FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'
    IGNORE 1 LINES
    (
        EVENT_ID,
	PARENT_EVENT_ID,
	EVENT_TYPE,
	EVENT_NAME,
	APPLICATION,
	EVENT_START,
	DURATION_NS,
	USER_ID,
	SESSION_ID,
	ERROR,
	EVENT_DATA
    )
