CREATE TABLE CASPR_EVENT_XML OF XMLType;

CREATE TABLE BEHAVIOR_TRACKING_EVENT
(
  EVENT_ID_PK	 NUMBER(16) NOT NULL PRIMARY KEY,
  EVENT_ID         VARCHAR2(100) NOT NULL,
  PARENT_EVENT_ID  VARCHAR2(100),
  EVENT_TYPE       VARCHAR2(20) NOT NULL,
  EVENT_NAME       VARCHAR2(256) NOT NULL,
  EVENT_START      DATE NOT NULL,
  USER_ID          VARCHAR2(64),
  SESSION_ID       VARCHAR2(64),
  APPLICATION      VARCHAR2(64) NOT NULL,
  DURATION_MS      NUMBER(16) NOT NULL,
  EVENT_DATA       CLOB,
  ERROR            VARCHAR2(256),
  SUMMARIZED       CHAR(1)
);

CREATE SEQUENCE SEQ_BEHAVIOR_TRACKING_EVENT
  START WITH 1
  MAXVALUE 9999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
  
CREATE TABLE BEHAVIOR_TRACKING_SUMMARY 
(
  ID	   		NUMBER(16) NOT NULL PRIMARY KEY,
  SUMMARY_DATE    VARCHAR2(100) NOT NULL,
  EVENT_TYPE      VARCHAR2(20) NOT NULL,
  EVENT_NAME      VARCHAR2(256) NOT NULL,
  PERIOD_START    DATE NOT NULL,
  PERIOD_END      DATE NOT NULL,
  COUNT          	NUMBER(16) NOT NULL,
  AVERAGE_MS	NUMBER(16,2) NOT NULL,
  MINIMUM_MS	NUMBER(16) NOT NULL,
  MAXIMUM_MS	NUMBER(16) NOT NULL,
  MEDIAN_MS		NUMBER(16) NOT NULL,
  STANDARD_DEVIATION NUMBER(16,2) NOT NULL,
  ERROR_COUNT 	NUMBER(16) NOT NULL  
);

CREATE SEQUENCE SEQ_BEHAVIOR_TRACKING_SUMMARY
  START WITH 1
  MAXVALUE 9999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
