-- staging table to receive XML event data.
create table BEHAVIOR_EVENT_XML of XMLType;


-- event data table for basic analysis.
create sequence SEQ_BEHAVIOR_TRACKING_EVENT;
create table BEHAVIOR_TRACKING_EVENT (
	EVENT_ID_PK		NUMBER(16)		PRIMARY KEY,
	EVENT_ID		VARCHAR2(100)	NOT NULL,
	PARENT_EVENT_ID	VARCHAR2(100),
	EVENT_TYPE		VARCHAR2(20)	NOT NULL,
	EVENT_NAME		VARCHAR2(256)	NOT NULL,
	EVENT_START		DATE			NOT NULL,
	USER_ID			VARCHAR2(64),
	SESSION_ID		VARCHAR2(64),
	APPLICATION		VARCHAR2(64)	NOT NULL,
	DURATION_MS		NUMBER(16)		NOT NULL,
	EVENT_DATA		CLOB,
	ERROR			VARCHAR2(256),
	SUMMARIZED		CHAR(1)
);
create index EVENT_NAME_IDX on BEHAVIOR_TRACKING_EVENT (
   EVENT_NAME ASC
);

-- event summary table for trending over long periods of time
create sequence SEQ_BEHAVIOR_TRACKING_SUMMARY;
create table BEHAVIOR_TRACKING_SUMMARY (
	ID					NUMBER(16)		PRIMARY KEY,
	SUMMARY_DATE		VARCHAR2(100)	NOT NULL,
	EVENT_TYPE			VARCHAR2(20)	NOT NULL,
	EVENT_NAME			VARCHAR2(256)	NOT NULL,
	PERIOD_START		DATE			NOT NULL,
	PERIOD_END			DATE			NOT NULL,
	"COUNT"				NUMBER(16)		NOT NULL,
	AVERAGE_MS			NUMBER(16)		NOT NULL,
	MINIMUM_MS			NUMBER(16)		NOT NULL,
	MAXIMUM_MS			NUMBER(16)		NOT NULL,
	MEDIAN_MS			NUMBER(16)		NOT NULL,
	STANDARD_DEVIATION	NUMBER(16)		NOT NULL,
	ERROR_COUNT			NUMBER(16)		NOT NULL
);

