LOAD DATA 
   INFILE *
   BADFILE 'BAD_EVENT_XML.txt' 
   DISCARDFILE 'DISCARD_EVENT_XML.txt' 
   APPEND
   CONTINUEIF LAST PRESERVE != "!"
INTO TABLE BEHAVIOR_EVENT_XML
XMLType(event_xml)
   FIELDS TERMINATED BY "!!" 
      (event_xml char(150000000))
