LOAD DATA 
   INFILE *
   BADFILE 'BAD_EVENT_XML.txt' 
   DISCARDFILE 'DISCARD_ EVENT_XML.txt' 
   APPEND
   CONTINUEIF LAST PRESERVE != "!"
INTO TABLE CASPR_EVENT_XML
XMLType(event_xml)
   FIELDS TERMINATED BY "!!" 
      (event_xml char(50000))