-- use with <jdbc-persister dialect="sequence" />
create sequence SEQ_BEHAVIOR_TRACKING_EVENT increment by 25;
create table BEHAVIOR_TRACKING_EVENT (
	EVENT_ID 		NUMERIC(10)		PRIMARY KEY,
	PARENT_EVENT_ID NUMERIC(10), 
	EVENT_TYPE		VARCHAR2(20)	NOT NULL,
	EVENT_NAME		VARCHAR2(256)	NOT NULL,
	EVENT_START		DATE			NOT NULL,
	USER_ID			VARCHAR2(64),
	SESSION_ID		VARCHAR2(64),
	APPLICATION		VARCHAR2(64)	NOT NULL,
	DURATION_NS		NUMBER(16)		NOT NULL,
	EVENT_DATA		CLOB,
	ERROR			VARCHAR2(512),
);
