create table BEHAVIOR_TRACKING_EVENT (
	EVENT_ID 		CHAR(36)		PRIMARY KEY,
	PARENT_EVENT_ID CHAR(36), 
	APPLICATION		VARCHAR2(32)	NOT NULL, 
	EVENT_TYPE			VARCHAR2(32)	NOT NULL, 
	EVENT_NAME			VARCHAR2(256)	NOT NULL, 
	EVENT_START			DATETIME		NOT NULL, 
	DURATION_NS		NUMERIC(10)		NOT NULL, 
	USER_ID			VARCHAR2(64), 
	SESSION_ID		VARCHAR2(64),
	ERROR			VARCHAR2(256), 
	EVENT_DATA		LONGVARCHAR
);
