create sequence S_BEHAVIOR_TRACKING_EVENT;
create table BEHAVIOR_TRACKING_EVENT (
	EVENT_ID 		NUMERIC(10)		PRIMARY KEY,
	PARENT_EVENT_ID NUMERIC(10), 
	APPLICATION		VARCHAR2(32)	NOT NULL, 
	TYPE			VARCHAR2(32)	NOT NULL, 
	NAME			VARCHAR2(256)	NOT NULL, 
	START			DATETIME		NOT NULL, 
	DURATION_MS		NUMERIC(10)		NOT NULL, 
	USER_ID			VARCHAR2(64), 
	SESSION_ID		VARCHAR2(64),
	ERROR			VARCHAR2(256), 
	DATA			VARCHAR2(2048)
);

create sequence S_BEHAVIOR_TRACKING_SUMMARY;
create table BEHAVIOR_TRACKING_SUMMARY (
	SUMMARY_ID			NUMERIC(10)		PRIMARY KEY,
	SUMMARY_DATE		DATETIME		NOT NULL,
	TYPE				VARCHAR2(32)	NOT NULL, 
	NAME				VARCHAR2(256)	NOT NULL, 
	PERIOD_START		DATETIME		NOT NULL,
	PERIOD_END			DATETIME		NOT NULL,
	EVENT_COUNT			NUMERIC(10)		NOT NULL,
	AVERAGE_MS			NUMERIC(10,2)	NOT NULL,
	MINIMUM_MS			NUMERIC(10)		NOT NULL,
	MAXIMUM_MS			NUMERIC(10)		NOT NULL,
	MEDIAN_MS			NUMERIC(10)		NOT NULL,
	STANDARD_DEVIATION	NUMERIC(10,2)	NOT NULL,
	ERROR_COUNT			NUMERIC(10)		NOT NULL
);