LOAD DATA 
   INFILE *
   BADFILE 'BAD_EVENT_XML.txt' 
   DISCARDFILE 'DISCARD_EVENT_XML.txt' 
   APPEND
INTO TABLE BEHAVIOR_EVENT_XML
XMLType(event_xml)
FIELDS (event_xml char(1000000)
	    TERMINATED BY '<!-- EOR -->')
